# render.yaml
services:
  - type: web
    name: fenetre-ouverte
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "1"
      - key: RAILS_MAX_THREADS
        value: "3"
      - key: FRONTEND_URL
        value: https://fenetre-ouverte.vercel.app
      - key: FRONTEND_ORIGIN
        value: https://fenetre-ouverte.vercel.app
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PRICE_CLIENT_MONTHLY
        sync: false
      - key: STRIPE_PRICE_MERCHANT_MONTHLY
        sync: false
      - key: STRIPE_PRICE_AGENCY_MONTHLY
        sync: false
